name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        
      - name: Configure project on windows
        if: startsWith(matrix.os, 'windows')
        run: qmake
        shell: cmd

      - name: Configure project on unix
        if: (!startsWith(matrix.os, 'windows'))
        run: qmake
        shell: bash
